### ISSUE TITLE
Setup Authentication/Encryption

### ISSUE THREAD

**Issue by nms377** [DEbinger/CEGS#32]
Setup authentication/encryption for users and setup routes for user/gallery

**Comment by DEbinger** [comment]
npm install the following dependencies (a few might not be needed):

passport
passport-http
passport-local
passport-instagram
passport-facebook
path
cookie-parser
express-session
bcryptjs
connect-flash

**Comment by DEbinger** [comment]
added .gitignore to ignore auth.js file with secret keys and id, added auth sample in its place.
 Added auth/passport.js for auth and made additions to server.js that includes passport. Need to confirm routes with Chaz.
