### ISSUE TITLE
Research D3 Globes

### ISSUE THREAD

**Issue by nms377** [DEbinger/CEGS#33]
Find globe visualization options for the landing page and the initial search page when the user searches for a city.

**Comment by gina3090** [comment]
Found some D3 globe/map samples.

**Comment by DEbinger** [comment]
This is a globe - https://bl.ocks.org/mbostock/ba63c55dd2dbc3ab0127

This is not a globe - https://bl.ocks.org/mbostock/2fb85b77236c24be5a6f
