### ISSUE TITLE
work on wire frames

### ISSUE THREAD

**Issue by Chaz-C** [DEbinger/CEGS#5]

**Comment by nms377** [comment]
Worked on finishing up the wireframe of our application. We completed the wireframe for the homepage, create user/login, flight/hotel/car selections, and itinerary overview.  We need to complete the wireframe for our user profile. We also need to create a wireframe for our travel album. The roadblock is defining what the travel album feature is and how it serves the user's experience. We also need to decide how we are going to collect the user's images. We talked about pulling the images from the user's Instagram account or allowing the user to upload images directly to the application.
